//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeeFashion.DataAccess.Repositories
{
    using System;
    using GeeFashion.DataModel;
    using GeeFashion.Model;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    
    public partial class WarehouseRepository : BaseRepository<Warehouse> 
    {
    	public WarehouseRepository(){}
    }
}
