//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeeFashion.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
    
    [DataContract]
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Item = new HashSet<Item>();
        }
    
        
    	[Key()]
    	[DataMember(Name = "Id")]
    	public int Id { get; set; }
        
    	[StringLength(50, ErrorMessage = "Name has a maximum length of 50.")]
    	[Required(ErrorMessage = "Name is required.")]
    	[DataMember(Name = "Name", IsRequired = true)]
    	public string Name { get; set; }
        
    	[Required(ErrorMessage = "Price is required.")]
    	[DataMember(Name = "Price", IsRequired = true)]
    	public decimal Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember(Name = "Item")]
    	public virtual ICollection<Item> Item { get; set; }
    }
}
